export const VERTICES_MIN_DISTANCE = 1e-3;
export const VERTICES_MAX_DISTANCE = 1e-2;
export const VERTICES_AUTO_CONNECT_DISTANCE = VERTICES_MAX_DISTANCE;
export const DELETE_VERTICES_MOUSE_DISTANCE = 10;
export const MINIMUM_NEW_VERTICES_PER_DRAW = 10;
export const DRAWN_POLYGON_COLOR_LIST = ['#c41d7f', '#531dab', '#096dd9', '#faad14', '#d4380d', '#08979c'];
