export enum DetectionTaskListSortOption {
  ID_ASCENDING = 0,
  ID_DESCENDING = 1,
  REQUEST_TIME_ASCENDING = 2,
  REQUEST_TIME_DESCENDING = 3,
  UPDATE_TIME_ASCENDING = 4,
  UPDATE_TIME_DESCENDING = 5,
}
