export enum ImageListSortOption {
  ID_ASCENDING = 0,
  ID_DESCENDING = 1,
  UPLOAD_TIME_ASCENDING = 2,
  UPLOAD_TIME_DESCENDING = 3,
  PUBLISH_TIME_ASCENDING = 4,
  PUBLISH_TIME_DESCENDING = 5,
  VERIFY_TIME_ASCENDING = 6,
  VERIFY_TIME_DESCENDING = 7,
}
